//ACTION TYPES;


//all users
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
//single user
export const FETCH_USER = "FETCH_USER";
export const ADD_USER= "ADD_USER";
export const DELETE_USER= "DELETE_USER";
export const EDIT_USER = "EDIT_USER";

//All moviesWatched
export const FETCH_ALL_MOVIESWATCHED = "FETCH_MOVIESWATCHED";
export const ADD_MOVIESWATCHED = "ADD_MOVIESWATCHED";
export const DELETE_MOVIESWATCHED = "DELETE_MOVIESWATCHED";
export const EDIT_MOVIESWATCHED= "EDIT_MOVIESWATCHED";
export const FETCH_MOVIESWATCHED= "FETCH_MOVIESWATCHED";
//All moviesWatching
export const FETCH_ALL_MOVIESWATCHING= "FETCH_ALL_MOVIESWATCHING";
export const ADD_MOVIESWATCHING = "ADD_MOVIESWATCHING";
export const DELETE_MOVIESWATCHING= "DELETE_MOVIESWATCHING";
export const EDIT_MOVIESWATCHING = "EDIT_MOVIESWATCHING";
export const FETCH_MOVIESWATCHING= "FETCH_MOVIESWATCHING";
